//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./runtests/csharp_lua/lua.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace lua {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IluaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class luaBaseListener : IluaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] luaParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] luaParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.start__y_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart__y_([NotNull] luaParser.Start__y_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.start__y_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart__y_([NotNull] luaParser.Start__y_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.nempty_list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_list_o_stat_p_([NotNull] luaParser.Nempty_list_o_stat_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.nempty_list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_list_o_stat_p_([NotNull] luaParser.Nempty_list_o_stat_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.allow_empty_o_nempty_list_o_stat_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_o_nempty_list_o_stat_p__p_([NotNull] luaParser.Allow_empty_o_nempty_list_o_stat_p__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.allow_empty_o_nempty_list_o_stat_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_o_nempty_list_o_stat_p__p_([NotNull] luaParser.Allow_empty_o_nempty_list_o_stat_p__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_o_stat_p_([NotNull] luaParser.List_o_stat_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_o_stat_p_([NotNull] luaParser.List_o_stat_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.opt_o_retstat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_retstat_p_([NotNull] luaParser.Opt_o_retstat_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.opt_o_retstat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_retstat_p_([NotNull] luaParser.Opt_o_retstat_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] luaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] luaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.opt_o__i__h__i__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o__i__h__i__p_([NotNull] luaParser.Opt_o__i__h__i__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.opt_o__i__h__i__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o__i__h__i__p_([NotNull] luaParser.Opt_o__i__h__i__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetstat([NotNull] luaParser.RetstatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetstat([NotNull] luaParser.RetstatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.nempty_list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_list_o_elseif_p_([NotNull] luaParser.Nempty_list_o_elseif_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.nempty_list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_list_o_elseif_p_([NotNull] luaParser.Nempty_list_o_elseif_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.allow_empty_o_nempty_list_o_elseif_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_o_nempty_list_o_elseif_p__p_([NotNull] luaParser.Allow_empty_o_nempty_list_o_elseif_p__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.allow_empty_o_nempty_list_o_elseif_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_o_nempty_list_o_elseif_p__p_([NotNull] luaParser.Allow_empty_o_nempty_list_o_elseif_p__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_o_elseif_p_([NotNull] luaParser.List_o_elseif_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_o_elseif_p_([NotNull] luaParser.List_o_elseif_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.opt_o_else_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_else_p_([NotNull] luaParser.Opt_o_else_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.opt_o_else_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_else_p_([NotNull] luaParser.Opt_o_else_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] luaParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] luaParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.opt_assign_rhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_assign_rhs([NotNull] luaParser.Opt_assign_rhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.opt_assign_rhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_assign_rhs([NotNull] luaParser.Opt_assign_rhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] luaParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] luaParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.range_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange_tail([NotNull] luaParser.Range_tailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.range_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange_tail([NotNull] luaParser.Range_tailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseif([NotNull] luaParser.ElseifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseif([NotNull] luaParser.ElseifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.else__x_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse__x_([NotNull] luaParser.Else__x_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.else__x_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse__x_([NotNull] luaParser.Else__x_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] luaParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] luaParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.binexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinexp([NotNull] luaParser.BinexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.binexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinexp([NotNull] luaParser.BinexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinseq([NotNull] luaParser.BinseqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinseq([NotNull] luaParser.BinseqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.binoperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinoperand([NotNull] luaParser.BinoperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.binoperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinoperand([NotNull] luaParser.BinoperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.unaryexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryexp([NotNull] luaParser.UnaryexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.unaryexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryexp([NotNull] luaParser.UnaryexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponent([NotNull] luaParser.ExponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponent([NotNull] luaParser.ExponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixexp([NotNull] luaParser.PrefixexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixexp([NotNull] luaParser.PrefixexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] luaParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] luaParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.nempty_seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_seplist_o__i__s__i__s_exp_p_([NotNull] luaParser.Nempty_seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.nempty_seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_seplist_o__i__s__i__s_exp_p_([NotNull] luaParser.Nempty_seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_([NotNull] luaParser.Allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_([NotNull] luaParser.Allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeplist_o__i__s__i__s_exp_p_([NotNull] luaParser.Seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeplist_o__i__s__i__s_exp_p_([NotNull] luaParser.Seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] luaParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] luaParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.opt_o_funcname_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_funcname_p_([NotNull] luaParser.Opt_o_funcname_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.opt_o_funcname_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_funcname_p_([NotNull] luaParser.Opt_o_funcname_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.opt_o_parlist_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_parlist_p_([NotNull] luaParser.Opt_o_parlist_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.opt_o_parlist_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_parlist_p_([NotNull] luaParser.Opt_o_parlist_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctiondef([NotNull] luaParser.FunctiondefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctiondef([NotNull] luaParser.FunctiondefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.varargs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarargs([NotNull] luaParser.VarargsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.varargs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarargs([NotNull] luaParser.VarargsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.nempty_seplist_o__i__s__i__s__i_name_k__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_seplist_o__i__s__i__s__i_name_k__p_([NotNull] luaParser.Nempty_seplist_o__i__s__i__s__i_name_k__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.nempty_seplist_o__i__s__i__s__i_name_k__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_seplist_o__i__s__i__s__i_name_k__p_([NotNull] luaParser.Nempty_seplist_o__i__s__i__s__i_name_k__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParlist([NotNull] luaParser.ParlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParlist([NotNull] luaParser.ParlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.nempty_seplist_o_fieldsep_s_field_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_seplist_o_fieldsep_s_field_p_([NotNull] luaParser.Nempty_seplist_o_fieldsep_s_field_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.nempty_seplist_o_fieldsep_s_field_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_seplist_o_fieldsep_s_field_p_([NotNull] luaParser.Nempty_seplist_o_fieldsep_s_field_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.opt_o_fieldsep_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_fieldsep_p_([NotNull] luaParser.Opt_o_fieldsep_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.opt_o_fieldsep_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_fieldsep_p_([NotNull] luaParser.Opt_o_fieldsep_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableconstructor([NotNull] luaParser.TableconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableconstructor([NotNull] luaParser.TableconstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncname([NotNull] luaParser.FuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncname([NotNull] luaParser.FuncnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] luaParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] luaParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsep([NotNull] luaParser.FieldsepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsep([NotNull] luaParser.FieldsepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="luaParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinop([NotNull] luaParser.BinopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="luaParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinop([NotNull] luaParser.BinopContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace lua
