//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./runtests/csharp_lua/Lua.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Lua {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILuaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LuaBaseListener : ILuaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] LuaParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] LuaParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.start__y_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart__y_([NotNull] LuaParser.Start__y_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.start__y_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart__y_([NotNull] LuaParser.Start__y_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_list_o_stat_p_([NotNull] LuaParser.Nempty_list_o_stat_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_list_o_stat_p_([NotNull] LuaParser.Nempty_list_o_stat_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_stat_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_o_nempty_list_o_stat_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_stat_p__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_stat_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_o_nempty_list_o_stat_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_stat_p__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_o_stat_p_([NotNull] LuaParser.List_o_stat_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.list_o_stat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_o_stat_p_([NotNull] LuaParser.List_o_stat_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_retstat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_retstat_p_([NotNull] LuaParser.Opt_o_retstat_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_retstat_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_retstat_p_([NotNull] LuaParser.Opt_o_retstat_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] LuaParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] LuaParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o__i__h__i__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o__i__h__i__p_([NotNull] LuaParser.Opt_o__i__h__i__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o__i__h__i__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o__i__h__i__p_([NotNull] LuaParser.Opt_o__i__h__i__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetstat([NotNull] LuaParser.RetstatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetstat([NotNull] LuaParser.RetstatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_list_o_elseif_p_([NotNull] LuaParser.Nempty_list_o_elseif_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_list_o_elseif_p_([NotNull] LuaParser.Nempty_list_o_elseif_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_elseif_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_o_nempty_list_o_elseif_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_elseif_p__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_elseif_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_o_nempty_list_o_elseif_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_elseif_p__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList_o_elseif_p_([NotNull] LuaParser.List_o_elseif_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.list_o_elseif_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList_o_elseif_p_([NotNull] LuaParser.List_o_elseif_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_else_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_else_p_([NotNull] LuaParser.Opt_o_else_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_else_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_else_p_([NotNull] LuaParser.Opt_o_else_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] LuaParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] LuaParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_assign_rhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_assign_rhs([NotNull] LuaParser.Opt_assign_rhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_assign_rhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_assign_rhs([NotNull] LuaParser.Opt_assign_rhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] LuaParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] LuaParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.range_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange_tail([NotNull] LuaParser.Range_tailContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.range_tail"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange_tail([NotNull] LuaParser.Range_tailContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseif([NotNull] LuaParser.ElseifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.elseif"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseif([NotNull] LuaParser.ElseifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.else__x_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse__x_([NotNull] LuaParser.Else__x_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.else__x_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse__x_([NotNull] LuaParser.Else__x_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] LuaParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] LuaParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinexp([NotNull] LuaParser.BinexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinexp([NotNull] LuaParser.BinexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinseq([NotNull] LuaParser.BinseqContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binseq"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinseq([NotNull] LuaParser.BinseqContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binoperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinoperand([NotNull] LuaParser.BinoperandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binoperand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinoperand([NotNull] LuaParser.BinoperandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.unaryexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryexp([NotNull] LuaParser.UnaryexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.unaryexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryexp([NotNull] LuaParser.UnaryexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExponent([NotNull] LuaParser.ExponentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exponent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExponent([NotNull] LuaParser.ExponentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixexp([NotNull] LuaParser.PrefixexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] LuaParser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] LuaParser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_seplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_seplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.seplist_o__i__s__i__s_exp_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Seplist_o__i__s__i__s_exp_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] LuaParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] LuaParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_funcname_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_funcname_p_([NotNull] LuaParser.Opt_o_funcname_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_funcname_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_funcname_p_([NotNull] LuaParser.Opt_o_funcname_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_parlist_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_parlist_p_([NotNull] LuaParser.Opt_o_parlist_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_parlist_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_parlist_p_([NotNull] LuaParser.Opt_o_parlist_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctiondef([NotNull] LuaParser.FunctiondefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varargs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarargs([NotNull] LuaParser.VarargsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varargs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarargs([NotNull] LuaParser.VarargsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s__i_name_k__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_seplist_o__i__s__i__s__i_name_k__p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s__i_name_k__p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s__i_name_k__p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_seplist_o__i__s__i__s__i_name_k__p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s__i_name_k__p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParlist([NotNull] LuaParser.ParlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParlist([NotNull] LuaParser.ParlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_seplist_o_fieldsep_s_field_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNempty_seplist_o_fieldsep_s_field_p_([NotNull] LuaParser.Nempty_seplist_o_fieldsep_s_field_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_seplist_o_fieldsep_s_field_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNempty_seplist_o_fieldsep_s_field_p_([NotNull] LuaParser.Nempty_seplist_o_fieldsep_s_field_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_fieldsep_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpt_o_fieldsep_p_([NotNull] LuaParser.Opt_o_fieldsep_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_fieldsep_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpt_o_fieldsep_p_([NotNull] LuaParser.Opt_o_fieldsep_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableconstructor([NotNull] LuaParser.TableconstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncname([NotNull] LuaParser.FuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncname([NotNull] LuaParser.FuncnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] LuaParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] LuaParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsep([NotNull] LuaParser.FieldsepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsep([NotNull] LuaParser.FieldsepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinop([NotNull] LuaParser.BinopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinop([NotNull] LuaParser.BinopContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Lua
