//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\runtests\csharp_lua\lua.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace lua {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class luaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, T__44=45, 
		T__45=46, T__46=47, T__47=48, T__48=49, T__49=50, T__50=51, T__51=52, 
		T__52=53, T__53=54, T__54=55, SPACE=56, NAME=57, NUMERAL=58, STR_LIT=59, 
		NESTED_STR=60;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "T__19", "T__20", "T__21", "T__22", "T__23", "T__24", 
		"T__25", "T__26", "T__27", "T__28", "T__29", "T__30", "T__31", "T__32", 
		"T__33", "T__34", "T__35", "T__36", "T__37", "T__38", "T__39", "T__40", 
		"T__41", "T__42", "T__43", "T__44", "T__45", "T__46", "T__47", "T__48", 
		"T__49", "T__50", "T__51", "T__52", "T__53", "T__54", "SPACE", "DIGIT", 
		"UCHAR", "NAME", "INT", "NUMERAL", "STR_LIT", "NESTED_STR1", "NESTED_STR2", 
		"NESTED_STR"
	};


	public static parameters paramsv (MyList<IToken> names,maybe<IToken> vararg)
	{
	    return (parameters) new parameters(names,vararg);
	}
	public static if_else if_else (IToken pos,block else_body)
	{
	    return (if_else) new if_else(pos,else_body);
	}
	public static if_elseif if_elseif (IToken pos,expr cond,block elif_body)
	{
	    return (if_elseif) new if_elseif(pos,cond,elif_body);
	}
	public static range range (expr low,expr high,maybe<expr> step)
	{
	    return (range) new range(low,high,step);
	}
	public static block block (MyList<stmt> suite,maybe<stmt> ret)
	{
	    return (block) new block(suite,ret);
	}
	public static expr Var (IToken value)
	{
	    return (expr) new Var(value);
	}
	public static expr UnsolvedBin (MyList<Op<expr>> value)
	{
	    return (expr) new UnsolvedBin(value);
	}
	public static expr TableExpr (table value1)
	{
	    return (expr) new TableExpr(value1);
	}
	public static expr String (IToken value1)
	{
	    return (expr) new String(value1);
	}
	public static expr Num (IToken value)
	{
	    return (expr) new Num(value);
	}
	public static expr Not (IToken value1,expr value2)
	{
	    return (expr) new Not(value1,value2);
	}
	public static expr Nil (IToken value)
	{
	    return (expr) new Nil(value);
	}
	public static expr NestedExp (IToken value1,expr value2)
	{
	    return (expr) new NestedExp(value1,value2);
	}
	public static expr Neg (IToken value1,expr value2)
	{
	    return (expr) new Neg(value1,value2);
	}
	public static expr Len (IToken value1,expr value2)
	{
	    return (expr) new Len(value1,value2);
	}
	public static expr Inv (IToken value1,expr value2)
	{
	    return (expr) new Inv(value1,value2);
	}
	public static expr Index (expr value1,expr value2)
	{
	    return (expr) new Index(value1,value2);
	}
	public static expr FuncDef (IToken pos,bool is_local,maybe<IToken> fname,maybe<parameters> parameters,block body)
	{
	    return (expr) new FuncDef(pos,is_local,fname,parameters,body);
	}
	public static expr Exponent (expr value1,expr value2)
	{
	    return (expr) new Exponent(value1,value2);
	}
	public static expr Ellipse (IToken value1)
	{
	    return (expr) new Ellipse(value1);
	}
	public static expr CallMethod (expr value1,IToken value2,arguments value3)
	{
	    return (expr) new CallMethod(value1,value2,value3);
	}
	public static expr CallFunc (expr value1,arguments value2)
	{
	    return (expr) new CallFunc(value1,value2);
	}
	public static expr Bool (IToken value1,bool value2)
	{
	    return (expr) new Bool(value1,value2);
	}
	public static expr Bin (IToken op,expr l,expr r)
	{
	    return (expr) new Bin(op,l,r);
	}
	public static expr Attr (expr value1,IToken value2)
	{
	    return (expr) new Attr(value1,value2);
	}
	public static stmt WhileStmt (IToken value1,expr value2,block value3)
	{
	    return (stmt) new WhileStmt(value1,value2,value3);
	}
	public static stmt ReturnStmt (IToken value1,MyList<expr> value2)
	{
	    return (stmt) new ReturnStmt(value1,value2);
	}
	public static stmt RepeatStmt (IToken value1,block value2,expr value3)
	{
	    return (stmt) new RepeatStmt(value1,value2,value3);
	}
	public static stmt LabelStmt (IToken value)
	{
	    return (stmt) new LabelStmt(value);
	}
	public static stmt IfStmt (IToken value1,expr value2,MyList<if_elseif> value3,maybe<if_else> value4)
	{
	    return (stmt) new IfStmt(value1,value2,value3,value4);
	}
	public static stmt GotoStmt (IToken value1,IToken value2)
	{
	    return (stmt) new GotoStmt(value1,value2);
	}
	public static stmt ForRangeStmt (IToken value1,IToken value2,range value3,block value4)
	{
	    return (stmt) new ForRangeStmt(value1,value2,value3,value4);
	}
	public static stmt ForInStmt (IToken value1,MyList<IToken> value2,MyList<expr> value3,block value4)
	{
	    return (stmt) new ForInStmt(value1,value2,value3,value4);
	}
	public static stmt ExprStmt (expr value)
	{
	    return (stmt) new ExprStmt(value);
	}
	public static stmt EmptyStmt (IToken value1)
	{
	    return (stmt) new EmptyStmt(value1);
	}
	public static stmt DoStmt (IToken value1,block value2)
	{
	    return (stmt) new DoStmt(value1,value2);
	}
	public static stmt BreakStmt (IToken value)
	{
	    return (stmt) new BreakStmt(value);
	}
	public static stmt Assignment (bool value1,MyList<expr> value2,maybe<MyList<expr>> value3)
	{
	    return (stmt) new Assignment(value1,value2,value3);
	}
	public static table_field NameField (IToken key,expr value)
	{
	    return (table_field) new NameField(key,value);
	}
	public static table_field IndexField (IToken pos,expr value,expr item)
	{
	    return (table_field) new IndexField(pos,value,item);
	}
	public static table_field ElementField (expr value1)
	{
	    return (table_field) new ElementField(value1);
	}
	public static table TableConstructor (IToken value1,MyList<table_field> value2)
	{
	    return (table) new TableConstructor(value1,value2);
	}
	public static arguments TableArgs (table value)
	{
	    return (arguments) new TableArgs(value);
	}
	public static arguments StringArg (IToken value)
	{
	    return (arguments) new StringArg(value);
	}
	public static arguments PositionalArgs (IToken value1,MyList<expr> value2)
	{
	    return (arguments) new PositionalArgs(value1,value2);
	}


	public luaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public luaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'return'", "'='", "'::'", "'break'", "'goto'", "'do'", "'end'", 
		"'while'", "'repeat'", "'until'", "'if'", "'then'", "'for'", "'in'", "'local'", 
		"'function'", "'('", "')'", "','", "'elseif'", "'else'", "'#'", "'-'", 
		"'~'", "'not'", "'^'", "':'", "'['", "']'", "'.'", "'nil'", "'false'", 
		"'true'", "'...'", "'{'", "'}'", "'or'", "'and'", "'<'", "'>'", "'<='", 
		"'>='", "'~='", "'=='", "'|'", "'&'", "'<<'", "'>>'", "'..'", "'+'", "'*'", 
		"'/'", "'//'", "'%'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, "SPACE", "NAME", "NUMERAL", 
		"STR_LIT", "NESTED_STR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "lua.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static luaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '>', '\x19C', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x4', '(', '\t', '(', '\x4', ')', 
		'\t', ')', '\x4', '*', '\t', '*', '\x4', '+', '\t', '+', '\x4', ',', '\t', 
		',', '\x4', '-', '\t', '-', '\x4', '.', '\t', '.', '\x4', '/', '\t', '/', 
		'\x4', '\x30', '\t', '\x30', '\x4', '\x31', '\t', '\x31', '\x4', '\x32', 
		'\t', '\x32', '\x4', '\x33', '\t', '\x33', '\x4', '\x34', '\t', '\x34', 
		'\x4', '\x35', '\t', '\x35', '\x4', '\x36', '\t', '\x36', '\x4', '\x37', 
		'\t', '\x37', '\x4', '\x38', '\t', '\x38', '\x4', '\x39', '\t', '\x39', 
		'\x4', ':', '\t', ':', '\x4', ';', '\t', ';', '\x4', '<', '\t', '<', '\x4', 
		'=', '\t', '=', '\x4', '>', '\t', '>', '\x4', '?', '\t', '?', '\x4', '@', 
		'\t', '@', '\x4', '\x41', '\t', '\x41', '\x4', '\x42', '\t', '\x42', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', 
		'!', '\x3', '!', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', 
		'\"', '\x3', '\"', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', 
		'#', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', '$', '\x3', '$', '\x3', 
		'$', '\x3', '%', '\x3', '%', '\x3', '&', '\x3', '&', '\x3', '\'', '\x3', 
		'\'', '\x3', '\'', '\x3', '(', '\x3', '(', '\x3', '(', '\x3', '(', '\x3', 
		')', '\x3', ')', '\x3', '*', '\x3', '*', '\x3', '+', '\x3', '+', '\x3', 
		'+', '\x3', ',', '\x3', ',', '\x3', ',', '\x3', '-', '\x3', '-', '\x3', 
		'-', '\x3', '.', '\x3', '.', '\x3', '.', '\x3', '/', '\x3', '/', '\x3', 
		'\x30', '\x3', '\x30', '\x3', '\x31', '\x3', '\x31', '\x3', '\x31', '\x3', 
		'\x32', '\x3', '\x32', '\x3', '\x32', '\x3', '\x33', '\x3', '\x33', '\x3', 
		'\x33', '\x3', '\x34', '\x3', '\x34', '\x3', '\x35', '\x3', '\x35', '\x3', 
		'\x36', '\x3', '\x36', '\x3', '\x37', '\x3', '\x37', '\x3', '\x37', '\x3', 
		'\x38', '\x3', '\x38', '\x3', '\x39', '\x3', '\x39', '\x3', '\x39', '\x3', 
		'\x39', '\x3', ':', '\x3', ':', '\x3', ';', '\x5', ';', '\x14A', '\n', 
		';', '\x3', '<', '\x3', '<', '\x3', '<', '\a', '<', '\x14F', '\n', '<', 
		'\f', '<', '\xE', '<', '\x152', '\v', '<', '\x3', '=', '\x6', '=', '\x155', 
		'\n', '=', '\r', '=', '\xE', '=', '\x156', '\x3', '>', '\x5', '>', '\x15A', 
		'\n', '>', '\x3', '>', '\x3', '>', '\x3', '>', '\x5', '>', '\x15F', '\n', 
		'>', '\x3', '>', '\x3', '>', '\x5', '>', '\x163', '\n', '>', '\x3', '?', 
		'\x3', '?', '\x3', '?', '\x3', '?', '\a', '?', '\x169', '\n', '?', '\f', 
		'?', '\xE', '?', '\x16C', '\v', '?', '\x3', '?', '\x3', '?', '\x3', '@', 
		'\x3', '@', '\x3', '@', '\x3', '@', '\a', '@', '\x174', '\n', '@', '\f', 
		'@', '\xE', '@', '\x177', '\v', '@', '\x3', '@', '\x3', '@', '\x3', '\x41', 
		'\x3', '\x41', '\x3', '\x41', '\x3', '\x41', '\x3', '\x41', '\x3', '\x41', 
		'\x3', '\x41', '\x5', '\x41', '\x182', '\n', '\x41', '\a', '\x41', '\x184', 
		'\n', '\x41', '\f', '\x41', '\xE', '\x41', '\x187', '\v', '\x41', '\x3', 
		'\x41', '\x3', '\x41', '\x3', '\x41', '\x3', '\x41', '\a', '\x41', '\x18D', 
		'\n', '\x41', '\f', '\x41', '\xE', '\x41', '\x190', '\v', '\x41', '\x5', 
		'\x41', '\x192', '\n', '\x41', '\x3', '\x41', '\x3', '\x41', '\x3', '\x42', 
		'\x3', '\x42', '\x3', '\x42', '\x5', '\x42', '\x199', '\n', '\x42', '\x3', 
		'\x42', '\x3', '\x42', '\x2', '\x2', '\x43', '\x3', '\x3', '\x5', '\x4', 
		'\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', 
		'\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', 
		'\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', 
		'\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', 
		'\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', 
		'\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', 
		'$', 'G', '%', 'I', '&', 'K', '\'', 'M', '(', 'O', ')', 'Q', '*', 'S', 
		'+', 'U', ',', 'W', '-', 'Y', '.', '[', '/', ']', '\x30', '_', '\x31', 
		'\x61', '\x32', '\x63', '\x33', '\x65', '\x34', 'g', '\x35', 'i', '\x36', 
		'k', '\x37', 'm', '\x38', 'o', '\x39', 'q', ':', 's', '\x2', 'u', '\x2', 
		'w', ';', 'y', '\x2', '{', '<', '}', '=', '\x7F', '\x2', '\x81', '\x2', 
		'\x83', '>', '\x3', '\x2', '\t', '\x5', '\x2', '\v', '\f', '\xF', '\xF', 
		'\"', '\"', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x3', '\x2', '$', 
		'$', '\x3', '\x2', '_', '_', '\x3', '\x2', '?', '?', '\x2', '\x1A7', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', 
		'\x3', '\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'I', '\x3', '\x2', '\x2', '\x2', '\x2', 'K', '\x3', '\x2', '\x2', '\x2', 
		'\x2', 'M', '\x3', '\x2', '\x2', '\x2', '\x2', 'O', '\x3', '\x2', '\x2', 
		'\x2', '\x2', 'Q', '\x3', '\x2', '\x2', '\x2', '\x2', 'S', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'U', '\x3', '\x2', '\x2', '\x2', '\x2', 'W', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'Y', '\x3', '\x2', '\x2', '\x2', '\x2', '[', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ']', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'_', '\x3', '\x2', '\x2', '\x2', '\x2', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x63', '\x3', '\x2', '\x2', '\x2', '\x2', '\x65', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'g', '\x3', '\x2', '\x2', '\x2', '\x2', 'i', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'k', '\x3', '\x2', '\x2', '\x2', '\x2', 'm', 
		'\x3', '\x2', '\x2', '\x2', '\x2', 'o', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'q', '\x3', '\x2', '\x2', '\x2', '\x2', 'w', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '{', '\x3', '\x2', '\x2', '\x2', '\x2', '}', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x83', '\x3', '\x2', '\x2', '\x2', '\x3', '\x85', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x87', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\t', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\v', '\x93', '\x3', '\x2', '\x2', '\x2', '\r', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\xF', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\x13', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\xAB', '\x3', '\x2', '\x2', '\x2', '\x17', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\xB8', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\xC4', '\x3', '\x2', '\x2', '\x2', '!', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '#', '\xCD', '\x3', '\x2', '\x2', '\x2', '%', '\xD6', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\xD8', '\x3', '\x2', '\x2', '\x2', 
		')', '\xDA', '\x3', '\x2', '\x2', '\x2', '+', '\xDC', '\x3', '\x2', '\x2', 
		'\x2', '-', '\xE3', '\x3', '\x2', '\x2', '\x2', '/', '\xE8', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\xEA', '\x3', '\x2', '\x2', '\x2', '\x33', '\xEC', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xEE', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xF2', '\x3', '\x2', '\x2', '\x2', '\x39', '\xF4', '\x3', '\x2', 
		'\x2', '\x2', ';', '\xF6', '\x3', '\x2', '\x2', '\x2', '=', '\xF8', '\x3', 
		'\x2', '\x2', '\x2', '?', '\xFA', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\xFC', '\x3', '\x2', '\x2', '\x2', '\x43', '\x100', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x106', '\x3', '\x2', '\x2', '\x2', 'G', '\x10B', '\x3', 
		'\x2', '\x2', '\x2', 'I', '\x10F', '\x3', '\x2', '\x2', '\x2', 'K', '\x111', 
		'\x3', '\x2', '\x2', '\x2', 'M', '\x113', '\x3', '\x2', '\x2', '\x2', 
		'O', '\x116', '\x3', '\x2', '\x2', '\x2', 'Q', '\x11A', '\x3', '\x2', 
		'\x2', '\x2', 'S', '\x11C', '\x3', '\x2', '\x2', '\x2', 'U', '\x11E', 
		'\x3', '\x2', '\x2', '\x2', 'W', '\x121', '\x3', '\x2', '\x2', '\x2', 
		'Y', '\x124', '\x3', '\x2', '\x2', '\x2', '[', '\x127', '\x3', '\x2', 
		'\x2', '\x2', ']', '\x12A', '\x3', '\x2', '\x2', '\x2', '_', '\x12C', 
		'\x3', '\x2', '\x2', '\x2', '\x61', '\x12E', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '\x131', '\x3', '\x2', '\x2', '\x2', '\x65', '\x134', '\x3', '\x2', 
		'\x2', '\x2', 'g', '\x137', '\x3', '\x2', '\x2', '\x2', 'i', '\x139', 
		'\x3', '\x2', '\x2', '\x2', 'k', '\x13B', '\x3', '\x2', '\x2', '\x2', 
		'm', '\x13D', '\x3', '\x2', '\x2', '\x2', 'o', '\x140', '\x3', '\x2', 
		'\x2', '\x2', 'q', '\x142', '\x3', '\x2', '\x2', '\x2', 's', '\x146', 
		'\x3', '\x2', '\x2', '\x2', 'u', '\x149', '\x3', '\x2', '\x2', '\x2', 
		'w', '\x14B', '\x3', '\x2', '\x2', '\x2', 'y', '\x154', '\x3', '\x2', 
		'\x2', '\x2', '{', '\x159', '\x3', '\x2', '\x2', '\x2', '}', '\x164', 
		'\x3', '\x2', '\x2', '\x2', '\x7F', '\x16F', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x17A', '\x3', '\x2', '\x2', '\x2', '\x83', '\x195', '\x3', '\x2', 
		'\x2', '\x2', '\x85', '\x86', '\a', '=', '\x2', '\x2', '\x86', '\x4', 
		'\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', 't', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'g', '\x2', '\x2', '\x89', '\x8A', '\a', 'v', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', 'w', '\x2', '\x2', '\x8B', '\x8C', '\a', 't', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', 'p', '\x2', '\x2', '\x8D', '\x6', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '?', '\x2', '\x2', '\x8F', 
		'\b', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\a', '<', '\x2', '\x2', 
		'\x91', '\x92', '\a', '<', '\x2', '\x2', '\x92', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\a', '\x64', '\x2', '\x2', '\x94', '\x95', '\a', 
		't', '\x2', '\x2', '\x95', '\x96', '\a', 'g', '\x2', '\x2', '\x96', '\x97', 
		'\a', '\x63', '\x2', '\x2', '\x97', '\x98', '\a', 'm', '\x2', '\x2', '\x98', 
		'\f', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', 'i', '\x2', '\x2', 
		'\x9A', '\x9B', '\a', 'q', '\x2', '\x2', '\x9B', '\x9C', '\a', 'v', '\x2', 
		'\x2', '\x9C', '\x9D', '\a', 'q', '\x2', '\x2', '\x9D', '\xE', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', '\x66', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', 'q', '\x2', '\x2', '\xA0', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA2', '\a', 'g', '\x2', '\x2', '\xA2', '\xA3', '\a', 
		'p', '\x2', '\x2', '\xA3', '\xA4', '\a', '\x66', '\x2', '\x2', '\xA4', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', 'y', '\x2', 
		'\x2', '\xA6', '\xA7', '\a', 'j', '\x2', '\x2', '\xA7', '\xA8', '\a', 
		'k', '\x2', '\x2', '\xA8', '\xA9', '\a', 'n', '\x2', '\x2', '\xA9', '\xAA', 
		'\a', 'g', '\x2', '\x2', '\xAA', '\x14', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xAC', '\a', 't', '\x2', '\x2', '\xAC', '\xAD', '\a', 'g', '\x2', '\x2', 
		'\xAD', '\xAE', '\a', 'r', '\x2', '\x2', '\xAE', '\xAF', '\a', 'g', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', '\x63', '\x2', '\x2', '\xB0', '\xB1', '\a', 
		'v', '\x2', '\x2', '\xB1', '\x16', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', 'w', '\x2', '\x2', '\xB3', '\xB4', '\a', 'p', '\x2', '\x2', 
		'\xB4', '\xB5', '\a', 'v', '\x2', '\x2', '\xB5', '\xB6', '\a', 'k', '\x2', 
		'\x2', '\xB6', '\xB7', '\a', 'n', '\x2', '\x2', '\xB7', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\xB8', '\xB9', '\a', 'k', '\x2', '\x2', '\xB9', 
		'\xBA', '\a', 'h', '\x2', '\x2', '\xBA', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\xBB', '\xBC', '\a', 'v', '\x2', '\x2', '\xBC', '\xBD', '\a', 
		'j', '\x2', '\x2', '\xBD', '\xBE', '\a', 'g', '\x2', '\x2', '\xBE', '\xBF', 
		'\a', 'p', '\x2', '\x2', '\xBF', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC1', '\a', 'h', '\x2', '\x2', '\xC1', '\xC2', '\a', 'q', '\x2', '\x2', 
		'\xC2', '\xC3', '\a', 't', '\x2', '\x2', '\xC3', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\xC4', '\xC5', '\a', 'k', '\x2', '\x2', '\xC5', '\xC6', 
		'\a', 'p', '\x2', '\x2', '\xC6', ' ', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC8', '\a', 'n', '\x2', '\x2', '\xC8', '\xC9', '\a', 'q', '\x2', '\x2', 
		'\xC9', '\xCA', '\a', '\x65', '\x2', '\x2', '\xCA', '\xCB', '\a', '\x63', 
		'\x2', '\x2', '\xCB', '\xCC', '\a', 'n', '\x2', '\x2', '\xCC', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCE', '\a', 'h', '\x2', '\x2', '\xCE', 
		'\xCF', '\a', 'w', '\x2', '\x2', '\xCF', '\xD0', '\a', 'p', '\x2', '\x2', 
		'\xD0', '\xD1', '\a', '\x65', '\x2', '\x2', '\xD1', '\xD2', '\a', 'v', 
		'\x2', '\x2', '\xD2', '\xD3', '\a', 'k', '\x2', '\x2', '\xD3', '\xD4', 
		'\a', 'q', '\x2', '\x2', '\xD4', '\xD5', '\a', 'p', '\x2', '\x2', '\xD5', 
		'$', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\a', '*', '\x2', '\x2', 
		'\xD7', '&', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', '\a', '+', '\x2', 
		'\x2', '\xD9', '(', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDB', '\a', 
		'.', '\x2', '\x2', '\xDB', '*', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', 
		'\a', 'g', '\x2', '\x2', '\xDD', '\xDE', '\a', 'n', '\x2', '\x2', '\xDE', 
		'\xDF', '\a', 'u', '\x2', '\x2', '\xDF', '\xE0', '\a', 'g', '\x2', '\x2', 
		'\xE0', '\xE1', '\a', 'k', '\x2', '\x2', '\xE1', '\xE2', '\a', 'h', '\x2', 
		'\x2', '\xE2', ',', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE4', '\a', 
		'g', '\x2', '\x2', '\xE4', '\xE5', '\a', 'n', '\x2', '\x2', '\xE5', '\xE6', 
		'\a', 'u', '\x2', '\x2', '\xE6', '\xE7', '\a', 'g', '\x2', '\x2', '\xE7', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xE8', '\xE9', '\a', '%', '\x2', '\x2', 
		'\xE9', '\x30', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xEB', '\a', '/', 
		'\x2', '\x2', '\xEB', '\x32', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', 
		'\a', '\x80', '\x2', '\x2', '\xED', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\xEE', '\xEF', '\a', 'p', '\x2', '\x2', '\xEF', '\xF0', '\a', 'q', '\x2', 
		'\x2', '\xF0', '\xF1', '\a', 'v', '\x2', '\x2', '\xF1', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\xF2', '\xF3', '\a', '`', '\x2', '\x2', '\xF3', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF5', '\a', '<', '\x2', 
		'\x2', '\xF5', ':', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', '\a', 
		']', '\x2', '\x2', '\xF7', '<', '\x3', '\x2', '\x2', '\x2', '\xF8', '\xF9', 
		'\a', '_', '\x2', '\x2', '\xF9', '>', '\x3', '\x2', '\x2', '\x2', '\xFA', 
		'\xFB', '\a', '\x30', '\x2', '\x2', '\xFB', '@', '\x3', '\x2', '\x2', 
		'\x2', '\xFC', '\xFD', '\a', 'p', '\x2', '\x2', '\xFD', '\xFE', '\a', 
		'k', '\x2', '\x2', '\xFE', '\xFF', '\a', 'n', '\x2', '\x2', '\xFF', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x100', '\x101', '\a', 'h', '\x2', '\x2', 
		'\x101', '\x102', '\a', '\x63', '\x2', '\x2', '\x102', '\x103', '\a', 
		'n', '\x2', '\x2', '\x103', '\x104', '\a', 'u', '\x2', '\x2', '\x104', 
		'\x105', '\a', 'g', '\x2', '\x2', '\x105', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x106', '\x107', '\a', 'v', '\x2', '\x2', '\x107', '\x108', '\a', 
		't', '\x2', '\x2', '\x108', '\x109', '\a', 'w', '\x2', '\x2', '\x109', 
		'\x10A', '\a', 'g', '\x2', '\x2', '\x10A', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\x10B', '\x10C', '\a', '\x30', '\x2', '\x2', '\x10C', '\x10D', 
		'\a', '\x30', '\x2', '\x2', '\x10D', '\x10E', '\a', '\x30', '\x2', '\x2', 
		'\x10E', 'H', '\x3', '\x2', '\x2', '\x2', '\x10F', '\x110', '\a', '}', 
		'\x2', '\x2', '\x110', 'J', '\x3', '\x2', '\x2', '\x2', '\x111', '\x112', 
		'\a', '\x7F', '\x2', '\x2', '\x112', 'L', '\x3', '\x2', '\x2', '\x2', 
		'\x113', '\x114', '\a', 'q', '\x2', '\x2', '\x114', '\x115', '\a', 't', 
		'\x2', '\x2', '\x115', 'N', '\x3', '\x2', '\x2', '\x2', '\x116', '\x117', 
		'\a', '\x63', '\x2', '\x2', '\x117', '\x118', '\a', 'p', '\x2', '\x2', 
		'\x118', '\x119', '\a', '\x66', '\x2', '\x2', '\x119', 'P', '\x3', '\x2', 
		'\x2', '\x2', '\x11A', '\x11B', '\a', '>', '\x2', '\x2', '\x11B', 'R', 
		'\x3', '\x2', '\x2', '\x2', '\x11C', '\x11D', '\a', '@', '\x2', '\x2', 
		'\x11D', 'T', '\x3', '\x2', '\x2', '\x2', '\x11E', '\x11F', '\a', '>', 
		'\x2', '\x2', '\x11F', '\x120', '\a', '?', '\x2', '\x2', '\x120', 'V', 
		'\x3', '\x2', '\x2', '\x2', '\x121', '\x122', '\a', '@', '\x2', '\x2', 
		'\x122', '\x123', '\a', '?', '\x2', '\x2', '\x123', 'X', '\x3', '\x2', 
		'\x2', '\x2', '\x124', '\x125', '\a', '\x80', '\x2', '\x2', '\x125', '\x126', 
		'\a', '?', '\x2', '\x2', '\x126', 'Z', '\x3', '\x2', '\x2', '\x2', '\x127', 
		'\x128', '\a', '?', '\x2', '\x2', '\x128', '\x129', '\a', '?', '\x2', 
		'\x2', '\x129', '\\', '\x3', '\x2', '\x2', '\x2', '\x12A', '\x12B', '\a', 
		'~', '\x2', '\x2', '\x12B', '^', '\x3', '\x2', '\x2', '\x2', '\x12C', 
		'\x12D', '\a', '(', '\x2', '\x2', '\x12D', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x12E', '\x12F', '\a', '>', '\x2', '\x2', '\x12F', '\x130', '\a', '>', 
		'\x2', '\x2', '\x130', '\x62', '\x3', '\x2', '\x2', '\x2', '\x131', '\x132', 
		'\a', '@', '\x2', '\x2', '\x132', '\x133', '\a', '@', '\x2', '\x2', '\x133', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x134', '\x135', '\a', '\x30', '\x2', 
		'\x2', '\x135', '\x136', '\a', '\x30', '\x2', '\x2', '\x136', '\x66', 
		'\x3', '\x2', '\x2', '\x2', '\x137', '\x138', '\a', '-', '\x2', '\x2', 
		'\x138', 'h', '\x3', '\x2', '\x2', '\x2', '\x139', '\x13A', '\a', ',', 
		'\x2', '\x2', '\x13A', 'j', '\x3', '\x2', '\x2', '\x2', '\x13B', '\x13C', 
		'\a', '\x31', '\x2', '\x2', '\x13C', 'l', '\x3', '\x2', '\x2', '\x2', 
		'\x13D', '\x13E', '\a', '\x31', '\x2', '\x2', '\x13E', '\x13F', '\a', 
		'\x31', '\x2', '\x2', '\x13F', 'n', '\x3', '\x2', '\x2', '\x2', '\x140', 
		'\x141', '\a', '\'', '\x2', '\x2', '\x141', 'p', '\x3', '\x2', '\x2', 
		'\x2', '\x142', '\x143', '\t', '\x2', '\x2', '\x2', '\x143', '\x144', 
		'\x3', '\x2', '\x2', '\x2', '\x144', '\x145', '\b', '\x39', '\x2', '\x2', 
		'\x145', 'r', '\x3', '\x2', '\x2', '\x2', '\x146', '\x147', '\t', '\x3', 
		'\x2', '\x2', '\x147', 't', '\x3', '\x2', '\x2', '\x2', '\x148', '\x14A', 
		'\t', '\x4', '\x2', '\x2', '\x149', '\x148', '\x3', '\x2', '\x2', '\x2', 
		'\x14A', 'v', '\x3', '\x2', '\x2', '\x2', '\x14B', '\x150', '\x5', 'u', 
		';', '\x2', '\x14C', '\x14F', '\x5', 'u', ';', '\x2', '\x14D', '\x14F', 
		'\x5', 's', ':', '\x2', '\x14E', '\x14C', '\x3', '\x2', '\x2', '\x2', 
		'\x14E', '\x14D', '\x3', '\x2', '\x2', '\x2', '\x14F', '\x152', '\x3', 
		'\x2', '\x2', '\x2', '\x150', '\x14E', '\x3', '\x2', '\x2', '\x2', '\x150', 
		'\x151', '\x3', '\x2', '\x2', '\x2', '\x151', 'x', '\x3', '\x2', '\x2', 
		'\x2', '\x152', '\x150', '\x3', '\x2', '\x2', '\x2', '\x153', '\x155', 
		'\x5', 's', ':', '\x2', '\x154', '\x153', '\x3', '\x2', '\x2', '\x2', 
		'\x155', '\x156', '\x3', '\x2', '\x2', '\x2', '\x156', '\x154', '\x3', 
		'\x2', '\x2', '\x2', '\x156', '\x157', '\x3', '\x2', '\x2', '\x2', '\x157', 
		'z', '\x3', '\x2', '\x2', '\x2', '\x158', '\x15A', '\a', '/', '\x2', '\x2', 
		'\x159', '\x158', '\x3', '\x2', '\x2', '\x2', '\x159', '\x15A', '\x3', 
		'\x2', '\x2', '\x2', '\x15A', '\x15B', '\x3', '\x2', '\x2', '\x2', '\x15B', 
		'\x15E', '\x5', 'y', '=', '\x2', '\x15C', '\x15D', '\a', '\x30', '\x2', 
		'\x2', '\x15D', '\x15F', '\x5', 'y', '=', '\x2', '\x15E', '\x15C', '\x3', 
		'\x2', '\x2', '\x2', '\x15E', '\x15F', '\x3', '\x2', '\x2', '\x2', '\x15F', 
		'\x162', '\x3', '\x2', '\x2', '\x2', '\x160', '\x161', '\t', '\x5', '\x2', 
		'\x2', '\x161', '\x163', '\x5', 'y', '=', '\x2', '\x162', '\x160', '\x3', 
		'\x2', '\x2', '\x2', '\x162', '\x163', '\x3', '\x2', '\x2', '\x2', '\x163', 
		'|', '\x3', '\x2', '\x2', '\x2', '\x164', '\x16A', '\a', '$', '\x2', '\x2', 
		'\x165', '\x166', '\a', '^', '\x2', '\x2', '\x166', '\x169', '\v', '\x2', 
		'\x2', '\x2', '\x167', '\x169', '\n', '\x6', '\x2', '\x2', '\x168', '\x165', 
		'\x3', '\x2', '\x2', '\x2', '\x168', '\x167', '\x3', '\x2', '\x2', '\x2', 
		'\x169', '\x16C', '\x3', '\x2', '\x2', '\x2', '\x16A', '\x168', '\x3', 
		'\x2', '\x2', '\x2', '\x16A', '\x16B', '\x3', '\x2', '\x2', '\x2', '\x16B', 
		'\x16D', '\x3', '\x2', '\x2', '\x2', '\x16C', '\x16A', '\x3', '\x2', '\x2', 
		'\x2', '\x16D', '\x16E', '\a', '$', '\x2', '\x2', '\x16E', '~', '\x3', 
		'\x2', '\x2', '\x2', '\x16F', '\x175', '\a', ']', '\x2', '\x2', '\x170', 
		'\x171', '\a', '_', '\x2', '\x2', '\x171', '\x174', '\n', '\a', '\x2', 
		'\x2', '\x172', '\x174', '\n', '\a', '\x2', '\x2', '\x173', '\x170', '\x3', 
		'\x2', '\x2', '\x2', '\x173', '\x172', '\x3', '\x2', '\x2', '\x2', '\x174', 
		'\x177', '\x3', '\x2', '\x2', '\x2', '\x175', '\x173', '\x3', '\x2', '\x2', 
		'\x2', '\x175', '\x176', '\x3', '\x2', '\x2', '\x2', '\x176', '\x178', 
		'\x3', '\x2', '\x2', '\x2', '\x177', '\x175', '\x3', '\x2', '\x2', '\x2', 
		'\x178', '\x179', '\a', '_', '\x2', '\x2', '\x179', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x17A', '\x191', '\a', '?', '\x2', '\x2', '\x17B', '\x185', 
		'\a', ']', '\x2', '\x2', '\x17C', '\x184', '\n', '\a', '\x2', '\x2', '\x17D', 
		'\x181', '\a', '_', '\x2', '\x2', '\x17E', '\x182', '\n', '\b', '\x2', 
		'\x2', '\x17F', '\x180', '\a', '?', '\x2', '\x2', '\x180', '\x182', '\n', 
		'\a', '\x2', '\x2', '\x181', '\x17E', '\x3', '\x2', '\x2', '\x2', '\x181', 
		'\x17F', '\x3', '\x2', '\x2', '\x2', '\x182', '\x184', '\x3', '\x2', '\x2', 
		'\x2', '\x183', '\x17C', '\x3', '\x2', '\x2', '\x2', '\x183', '\x17D', 
		'\x3', '\x2', '\x2', '\x2', '\x184', '\x187', '\x3', '\x2', '\x2', '\x2', 
		'\x185', '\x183', '\x3', '\x2', '\x2', '\x2', '\x185', '\x186', '\x3', 
		'\x2', '\x2', '\x2', '\x186', '\x188', '\x3', '\x2', '\x2', '\x2', '\x187', 
		'\x185', '\x3', '\x2', '\x2', '\x2', '\x188', '\x192', '\a', '_', '\x2', 
		'\x2', '\x189', '\x18A', '\a', '?', '\x2', '\x2', '\x18A', '\x18D', '\n', 
		'\a', '\x2', '\x2', '\x18B', '\x18D', '\n', '\b', '\x2', '\x2', '\x18C', 
		'\x189', '\x3', '\x2', '\x2', '\x2', '\x18C', '\x18B', '\x3', '\x2', '\x2', 
		'\x2', '\x18D', '\x190', '\x3', '\x2', '\x2', '\x2', '\x18E', '\x18C', 
		'\x3', '\x2', '\x2', '\x2', '\x18E', '\x18F', '\x3', '\x2', '\x2', '\x2', 
		'\x18F', '\x192', '\x3', '\x2', '\x2', '\x2', '\x190', '\x18E', '\x3', 
		'\x2', '\x2', '\x2', '\x191', '\x17B', '\x3', '\x2', '\x2', '\x2', '\x191', 
		'\x18E', '\x3', '\x2', '\x2', '\x2', '\x192', '\x193', '\x3', '\x2', '\x2', 
		'\x2', '\x193', '\x194', '\a', '?', '\x2', '\x2', '\x194', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x195', '\x198', '\a', ']', '\x2', '\x2', '\x196', 
		'\x199', '\x5', '\x7F', '@', '\x2', '\x197', '\x199', '\x5', '\x81', '\x41', 
		'\x2', '\x198', '\x196', '\x3', '\x2', '\x2', '\x2', '\x198', '\x197', 
		'\x3', '\x2', '\x2', '\x2', '\x199', '\x19A', '\x3', '\x2', '\x2', '\x2', 
		'\x19A', '\x19B', '\a', '_', '\x2', '\x2', '\x19B', '\x84', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x2', '\x149', '\x14E', '\x150', '\x156', '\x159', 
		'\x15E', '\x162', '\x168', '\x16A', '\x173', '\x175', '\x181', '\x183', 
		'\x185', '\x18C', '\x18E', '\x191', '\x198', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace lua
