//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./runtests/csharp_lua/Lua.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Lua {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LuaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILuaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] LuaParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] LuaParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.start__y_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart__y_([NotNull] LuaParser.Start__y_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.start__y_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart__y_([NotNull] LuaParser.Start__y_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_list_o_stat_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNempty_list_o_stat_p_([NotNull] LuaParser.Nempty_list_o_stat_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_list_o_stat_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNempty_list_o_stat_p_([NotNull] LuaParser.Nempty_list_o_stat_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_stat_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllow_empty_o_nempty_list_o_stat_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_stat_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_stat_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllow_empty_o_nempty_list_o_stat_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_stat_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.list_o_stat_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_o_stat_p_([NotNull] LuaParser.List_o_stat_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.list_o_stat_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_o_stat_p_([NotNull] LuaParser.List_o_stat_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_retstat_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpt_o_retstat_p_([NotNull] LuaParser.Opt_o_retstat_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_retstat_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpt_o_retstat_p_([NotNull] LuaParser.Opt_o_retstat_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] LuaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] LuaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o__i__h__i__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpt_o__i__h__i__p_([NotNull] LuaParser.Opt_o__i__h__i__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o__i__h__i__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpt_o__i__h__i__p_([NotNull] LuaParser.Opt_o__i__h__i__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRetstat([NotNull] LuaParser.RetstatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.retstat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRetstat([NotNull] LuaParser.RetstatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_list_o_elseif_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNempty_list_o_elseif_p_([NotNull] LuaParser.Nempty_list_o_elseif_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_list_o_elseif_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNempty_list_o_elseif_p_([NotNull] LuaParser.Nempty_list_o_elseif_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_elseif_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllow_empty_o_nempty_list_o_elseif_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_elseif_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_list_o_elseif_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllow_empty_o_nempty_list_o_elseif_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_list_o_elseif_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.list_o_elseif_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_o_elseif_p_([NotNull] LuaParser.List_o_elseif_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.list_o_elseif_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_o_elseif_p_([NotNull] LuaParser.List_o_elseif_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_else_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpt_o_else_p_([NotNull] LuaParser.Opt_o_else_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_else_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpt_o_else_p_([NotNull] LuaParser.Opt_o_else_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] LuaParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] LuaParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_assign_rhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpt_assign_rhs([NotNull] LuaParser.Opt_assign_rhsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_assign_rhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpt_assign_rhs([NotNull] LuaParser.Opt_assign_rhsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] LuaParser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] LuaParser.RangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.range_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange_tail([NotNull] LuaParser.Range_tailContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.range_tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange_tail([NotNull] LuaParser.Range_tailContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.elseif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseif([NotNull] LuaParser.ElseifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.elseif"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseif([NotNull] LuaParser.ElseifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.else__x_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse__x_([NotNull] LuaParser.Else__x_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.else__x_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse__x_([NotNull] LuaParser.Else__x_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] LuaParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] LuaParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinexp([NotNull] LuaParser.BinexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinexp([NotNull] LuaParser.BinexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinseq([NotNull] LuaParser.BinseqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinseq([NotNull] LuaParser.BinseqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binoperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinoperand([NotNull] LuaParser.BinoperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binoperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinoperand([NotNull] LuaParser.BinoperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.unaryexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryexp([NotNull] LuaParser.UnaryexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.unaryexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryexp([NotNull] LuaParser.UnaryexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.exponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExponent([NotNull] LuaParser.ExponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.exponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExponent([NotNull] LuaParser.ExponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixexp([NotNull] LuaParser.PrefixexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.prefixexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixexp([NotNull] LuaParser.PrefixexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] LuaParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] LuaParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s_exp_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNempty_seplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s_exp_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s_exp_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNempty_seplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s_exp_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_([NotNull] LuaParser.Allow_empty_o_nempty_seplist_o__i__s__i__s_exp_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.seplist_o__i__s__i__s_exp_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Seplist_o__i__s__i__s_exp_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.seplist_o__i__s__i__s_exp_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeplist_o__i__s__i__s_exp_p_([NotNull] LuaParser.Seplist_o__i__s__i__s_exp_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] LuaParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] LuaParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_funcname_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpt_o_funcname_p_([NotNull] LuaParser.Opt_o_funcname_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_funcname_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpt_o_funcname_p_([NotNull] LuaParser.Opt_o_funcname_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_parlist_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpt_o_parlist_p_([NotNull] LuaParser.Opt_o_parlist_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_parlist_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpt_o_parlist_p_([NotNull] LuaParser.Opt_o_parlist_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctiondef([NotNull] LuaParser.FunctiondefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.functiondef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctiondef([NotNull] LuaParser.FunctiondefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.varargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarargs([NotNull] LuaParser.VarargsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.varargs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarargs([NotNull] LuaParser.VarargsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s__i_name_k__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNempty_seplist_o__i__s__i__s__i_name_k__p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s__i_name_k__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_seplist_o__i__s__i__s__i_name_k__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNempty_seplist_o__i__s__i__s__i_name_k__p_([NotNull] LuaParser.Nempty_seplist_o__i__s__i__s__i_name_k__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParlist([NotNull] LuaParser.ParlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.parlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParlist([NotNull] LuaParser.ParlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.nempty_seplist_o_fieldsep_s_field_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNempty_seplist_o_fieldsep_s_field_p_([NotNull] LuaParser.Nempty_seplist_o_fieldsep_s_field_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.nempty_seplist_o_fieldsep_s_field_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNempty_seplist_o_fieldsep_s_field_p_([NotNull] LuaParser.Nempty_seplist_o_fieldsep_s_field_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.opt_o_fieldsep_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpt_o_fieldsep_p_([NotNull] LuaParser.Opt_o_fieldsep_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.opt_o_fieldsep_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpt_o_fieldsep_p_([NotNull] LuaParser.Opt_o_fieldsep_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTableconstructor([NotNull] LuaParser.TableconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.tableconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTableconstructor([NotNull] LuaParser.TableconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncname([NotNull] LuaParser.FuncnameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.funcname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncname([NotNull] LuaParser.FuncnameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] LuaParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] LuaParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldsep([NotNull] LuaParser.FieldsepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.fieldsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldsep([NotNull] LuaParser.FieldsepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LuaParser.binop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinop([NotNull] LuaParser.BinopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LuaParser.binop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinop([NotNull] LuaParser.BinopContext context);
}
} // namespace Lua
