//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./CLI/Grammar/TypedBNF.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace TypedBNF {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TypedBNFParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ITypedBNFListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] TypedBNFParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] TypedBNFParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.list_o_toplevel_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_o_toplevel_p_([NotNull] TypedBNFParser.List_o_toplevel_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.list_o_toplevel_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_o_toplevel_p_([NotNull] TypedBNFParser.List_o_toplevel_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.start__y_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart__y_([NotNull] TypedBNFParser.Start__y_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.start__y_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart__y_([NotNull] TypedBNFParser.Start__y_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.identstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentstr([NotNull] TypedBNFParser.IdentstrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.identstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentstr([NotNull] TypedBNFParser.IdentstrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyp([NotNull] TypedBNFParser.TypContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyp([NotNull] TypedBNFParser.TypContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_param_type_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_param_type_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_param_type_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_param_type_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_param_type_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_param_type_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_param_type_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_o_slist_o__i__s__i__s_param_type_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_param_type_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_param_type_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_o_slist_o__i__s__i__s_param_type_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_param_type_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_param_type_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEslist_o__i__s__i__s_param_type_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_param_type_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_param_type_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEslist_o__i__s__i__s_param_type_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_param_type_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.arrow_typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrow_typ([NotNull] TypedBNFParser.Arrow_typContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.arrow_typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrow_typ([NotNull] TypedBNFParser.Arrow_typContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_typ_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_typ_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_typ_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_typ_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_typ_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_typ_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.typ2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTyp2([NotNull] TypedBNFParser.Typ2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.typ2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTyp2([NotNull] TypedBNFParser.Typ2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.type_product"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_product([NotNull] TypedBNFParser.Type_productContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.type_product"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_product([NotNull] TypedBNFParser.Type_productContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.top_typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_typ([NotNull] TypedBNFParser.Top_typContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.top_typ"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_typ([NotNull] TypedBNFParser.Top_typContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.tvar_str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTvar_str([NotNull] TypedBNFParser.Tvar_strContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.tvar_str"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTvar_str([NotNull] TypedBNFParser.Tvar_strContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.param_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_type([NotNull] TypedBNFParser.Param_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.param_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_type([NotNull] TypedBNFParser.Param_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_tvar_str_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_tvar_str_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_tvar_str_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_tvar_str_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_tvar_str_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_tvar_str_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.type_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_params([NotNull] TypedBNFParser.Type_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.type_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_params([NotNull] TypedBNFParser.Type_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.field_ann"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_ann([NotNull] TypedBNFParser.Field_annContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.field_ann"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_ann([NotNull] TypedBNFParser.Field_annContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_field_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_field_ann_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_field_ann_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_field_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_field_ann_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_field_ann_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_field_ann_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_o_slist_o__i__s__i__s_field_ann_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_field_ann_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_field_ann_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_o_slist_o__i__s__i__s_field_ann_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_field_ann_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_field_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEslist_o__i__s__i__s_field_ann_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_field_ann_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_field_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEslist_o__i__s__i__s_field_ann_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_field_ann_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.field_anns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_anns([NotNull] TypedBNFParser.Field_annsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.field_anns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_anns([NotNull] TypedBNFParser.Field_annsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecl([NotNull] TypedBNFParser.DeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecl([NotNull] TypedBNFParser.DeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.toplevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterToplevel([NotNull] TypedBNFParser.ToplevelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.toplevel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitToplevel([NotNull] TypedBNFParser.ToplevelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_identstr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_identstr_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_identstr_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_identstr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_identstr_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_identstr_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDef([NotNull] TypedBNFParser.DefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDef([NotNull] TypedBNFParser.DefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.productions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProductions([NotNull] TypedBNFParser.ProductionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.productions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProductions([NotNull] TypedBNFParser.ProductionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.list_o_psym_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_o_psym_p_([NotNull] TypedBNFParser.List_o_psym_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.list_o_psym_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_o_psym_p_([NotNull] TypedBNFParser.List_o_psym_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.empty_o_list_o_psym_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_o_list_o_psym_p__p_([NotNull] TypedBNFParser.Empty_o_list_o_psym_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.empty_o_list_o_psym_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_o_list_o_psym_p__p_([NotNull] TypedBNFParser.Empty_o_list_o_psym_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.elist_o_psym_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElist_o_psym_p_([NotNull] TypedBNFParser.Elist_o_psym_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.elist_o_psym_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElist_o_psym_p_([NotNull] TypedBNFParser.Elist_o_psym_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProduction([NotNull] TypedBNFParser.ProductionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.production"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProduction([NotNull] TypedBNFParser.ProductionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_psym_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_psym_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_psym_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_psym_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_psym_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_psym_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.psym"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPsym([NotNull] TypedBNFParser.PsymContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.psym"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPsym([NotNull] TypedBNFParser.PsymContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.ann"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnn([NotNull] TypedBNFParser.AnnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.ann"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnn([NotNull] TypedBNFParser.AnnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_ann_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_ann_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_ann_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_ann_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_ann_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_o_slist_o__i__s__i__s_ann_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_ann_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_ann_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_o_slist_o__i__s__i__s_ann_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_ann_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEslist_o__i__s__i__s_ann_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_ann_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_ann_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEslist_o__i__s__i__s_ann_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_ann_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.func_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_parameters([NotNull] TypedBNFParser.Func_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.func_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_parameters([NotNull] TypedBNFParser.Func_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] TypedBNFParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] TypedBNFParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] TypedBNFParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] TypedBNFParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_expr_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_o_slist_o__i__s__i__s_expr_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_expr_p__p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.empty_o_slist_o__i__s__i__s_expr_p__p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_o_slist_o__i__s__i__s_expr_p__p_([NotNull] TypedBNFParser.Empty_o_slist_o__i__s__i__s_expr_p__p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_expr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEslist_o__i__s__i__s_expr_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_expr_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.eslist_o__i__s__i__s_expr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEslist_o__i__s__i__s_expr_p_([NotNull] TypedBNFParser.Eslist_o__i__s__i__s_expr_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_expr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__s__i__s_expr_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_expr_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__s__i__s_expr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__s__i__s_expr_p_([NotNull] TypedBNFParser.Slist_o__i__s__i__s_expr_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.atomexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomexp([NotNull] TypedBNFParser.AtomexpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.atomexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomexp([NotNull] TypedBNFParser.AtomexpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.slist_o__i__u__i__s_lexer_and_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlist_o__i__u__i__s_lexer_and_p_([NotNull] TypedBNFParser.Slist_o__i__u__i__s_lexer_and_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.slist_o__i__u__i__s_lexer_and_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlist_o__i__u__i__s_lexer_and_p_([NotNull] TypedBNFParser.Slist_o__i__u__i__s_lexer_and_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.lexer__y_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexer__y_([NotNull] TypedBNFParser.Lexer__y_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.lexer__y_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexer__y_([NotNull] TypedBNFParser.Lexer__y_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.list_o_lexer_atomexpr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList_o_lexer_atomexpr_p_([NotNull] TypedBNFParser.List_o_lexer_atomexpr_p_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.list_o_lexer_atomexpr_p_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList_o_lexer_atomexpr_p_([NotNull] TypedBNFParser.List_o_lexer_atomexpr_p_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.lexer_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexer_and([NotNull] TypedBNFParser.Lexer_andContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.lexer_and"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexer_and([NotNull] TypedBNFParser.Lexer_andContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.lexer_atomexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexer_atomexpr([NotNull] TypedBNFParser.Lexer_atomexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.lexer_atomexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexer_atomexpr([NotNull] TypedBNFParser.Lexer_atomexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.lexer_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexer_atom([NotNull] TypedBNFParser.Lexer_atomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.lexer_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexer_atom([NotNull] TypedBNFParser.Lexer_atomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TypedBNFParser.lexerdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexerdef([NotNull] TypedBNFParser.LexerdefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TypedBNFParser.lexerdef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexerdef([NotNull] TypedBNFParser.LexerdefContext context);
}
} // namespace TypedBNF
