//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./runtests/csharp_simple_json/simple_json.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace simple_json {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Isimple_jsonListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class simple_jsonBaseListener : Isimple_jsonListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="simple_jsonParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] simple_jsonParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="simple_jsonParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] simple_jsonParser.StartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="simple_jsonParser.start__y_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart__y_([NotNull] simple_jsonParser.Start__y_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="simple_jsonParser.start__y_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart__y_([NotNull] simple_jsonParser.Start__y_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="simple_jsonParser.jsonpair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsonpair([NotNull] simple_jsonParser.JsonpairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="simple_jsonParser.jsonpair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsonpair([NotNull] simple_jsonParser.JsonpairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="simple_jsonParser.seplist_o__i__s__i__s_json_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeplist_o__i__s__i__s_json_p_([NotNull] simple_jsonParser.Seplist_o__i__s__i__s_json_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="simple_jsonParser.seplist_o__i__s__i__s_json_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeplist_o__i__s__i__s_json_p_([NotNull] simple_jsonParser.Seplist_o__i__s__i__s_json_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="simple_jsonParser.seplist_o__i__s__i__s_jsonpair_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSeplist_o__i__s__i__s_jsonpair_p_([NotNull] simple_jsonParser.Seplist_o__i__s__i__s_jsonpair_p_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="simple_jsonParser.seplist_o__i__s__i__s_jsonpair_p_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSeplist_o__i__s__i__s_jsonpair_p_([NotNull] simple_jsonParser.Seplist_o__i__s__i__s_jsonpair_p_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="simple_jsonParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJson([NotNull] simple_jsonParser.JsonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="simple_jsonParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJson([NotNull] simple_jsonParser.JsonContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace simple_json
